name: Build Release

on:
  push:
    branches: [ "github-actions" ]
  pull_request:
    branches: [ "github-actions" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.LIBARTBASE_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBARTPALETTE_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBBASE_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBCUTILS_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBDEXFILE_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBLOG_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBSYSTEM_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBTINYXML2_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBUNWINDSTACK_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBUTILS_PRIVATE_SSH_KEY }}
          ${{ secrets.LIBZIPARCHIVE_PRIVATE_SSH_KEY }}
          ${{ secrets.LZMA_PRIVATE_SSH_KEY }}
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
    - name: cache-conan-packages
      id: conan-aarch64-cache
      uses: actions/cache@v3
      with:
        path: ~/.conan/data
        key: ${{ runner.os }}-aarch64-conanpackages-${{ hashFiles('./build/aarch64/conanfile.txt') }}
    - name: make-aarch64-build-directory
      run: mkdir ./build/aarch64/cmake-build-release
    - name: conan-aarch64
      working-directory: ./build/aarch64/cmake-build-release
      run: conan install ../conanfile.txt --profile:build ../build.profile --profile:host ../armv8.profile --build missing
    - name: cmake-aarch64
      working-directory: ./build/aarch64/cmake-build-release
      run: cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
    - name: make-aarch64
      working-directory: ./build/aarch64/cmake-build-release
      run: make
#    - name: conan-x86
#      run: cd - && mkdir ./build/x86_64/cmake-build-release && cd ./build/x86_64/cmake-build-release && conan install ../conanfile.txt --profile:build ../build.profile --profile:host ../armv8.profile
#    - name: cmake-x86
#      run: cmake .. -DCMAKE_BUILD_TYPE=Release
#    - name: make-x86
#      run: make
